% Test getParameters

clc;
clear;

linkConfig = {...
    {'spanLength', 80e3, 'DCFLength', 80e3}, ...
    {'spanLength', 90e3, 'DCFLength', 90e3}...
    };
channelConfig = {...
    {'modulation', 'OOK', ...
    'symbolRate', 10, ...
    'centerFrequency', -50e9, ...
    'filterFactor', 0.65, ...
    'minSamplePerSymbol', 4},...
    {'modulation', '16QAM', ...
    'symbolRate', 32, ...
    'centerFrequency', 0e9, ...
    'filterFactor', 0.2, ...
    'minSamplePerSymbol', 8},...
    {'modulation', 'OOK', ...
    'symbolRate', 10, ...
    'centerFrequency', 50e9, ...
    'filterFactor', 0.65, ...
    'minSamplePerSymbol', 4},...
    };
% [param, p] = getParameters(...
%     'randomSeed', 1, ...
%     'resultsFolder', 'testResults', ...
%     'logFileName', 'testLog', ...
%     'spanLength', 82e3, ...
%     'D', 17e-6, ...
%     'DCFLength', 82e3, ...
%     'linkConfig', linkConfig, ...
%     'S', 0, ...
%     'alphaIndB', 0.002, ...
%     'gamma', 0.0014, ...
%     'numberSteps', 100, ...
%     'NFdB', 5.5, ...
%     'DCFLength', 80, ...
%     'modulation', '16QAM', ...
%     'symbolRate', 32, ...
%     'centerFrequency', 50e9, ...
%     'filterFactor', 0.2, ...
%     'minSamplePerSymbol', 64);

% [param, p] = getParameters(...
%     'randomSeed', 1, ...
%     'resultsFolder', 'testResults', ...
%     'logFileName', 'testLog', ...
%     'spanLength', 82e3, ...
%     'D', 17e-6, ...
%     'DCFLength', 82e3, ...
%     'numberLink', 3, ...
%     'S', 0, ...
%     'alphaIndB', 0.002, ...
%     'gamma', 0.0014, ...
%     'numberSteps', 100, ...
%     'NFdB', 5.5, ...
%     'DCFLength', 80, ...
%     'modulation', '16QAM', ...
%     'symbolRate', 32, ...
%     'centerFrequency', 50e9, ...
%     'filterFactor', 0.2, ...
%     'minSamplePerSymbol', 64);

[param, p] = getParameters(...
    'randomSeed', 1, ...
    'resultsFolder', 'testResults', ...
    'logFileName', 'testLog', ...
    'spanLength', 82e3, ...
    'D', 17e-6, ...
    'DCFLength', 82e3, ...
    'numberLink', 3, ...
    'S', 0, ...
    'alphaIndB', 0.002, ...
    'gamma', 0.0014, ...
    'numberSteps', 100, ...
    'NFdB', 5.5, ...
    'DCFLength', 80, ...
    'modulation', '16QAM', ...
    'symbolRate', 32, ...
    'centerFrequency', 50e9, ...
    'filterFactor', 0.2, ...
    'minSamplePerSymbol', 64, ...
    'channelConfig', channelConfig);