%% Transmit a single QAM in 5 spans of fibers

clc;
close all;
clear;

%% Sweep power
spArray = SinglePolarization();
% QAMSnrdB = zeros(size(QAMPowerdBm));
for n=1:1
    linkArray = [Link('alphadB', 0.3e-3, 'gamma', 6e-3)];
    channelArray = [Channel(...
        'powerdBm', -4, ...
        'modulation', '16QAM', ...
        'firFactor', 0.2, ...
        'minNumberSymbol', 4096, ...
        'symbolRate', 30e9); ...
%         Channel(...
%         'powerdBm', qamPowerdBm(n), ...
%         'modulation', '16QAM', ...
%         'firFactor', 0.2, ...
%         'minNumberSymbol', 4096, ...
%         'symbolRate', 30e9, ...
%         'centerFrequency', 50e9)...
        ];
    
    sp = SinglePolarization(...
        'simulationName', 'testSingleQAM', ...
        'simulationId', 1, ...
        'randomSeed', 0, ...
        'linkArray', linkArray, ...
        'channelArray', channelArray, ...
        'useParallel', false);
    sp.simulate();
    spArray(n) = sp;
    fprintf('SNR = %2.2f dB\n', sp.channelArray.SNRdB);
end

%% Spectrum
% h1 = plotSpectrum(sp, 'tx', 1);
% h2 = plotSpectrum(sp, 'current', 2);

%% Eye
% close all;
% plot(rem(sp.t, sp.channelArray.actualSamplePerSymbol*sp.dt*2), imag(sp.channelArray.txTime), '.', 'markersize', 1)
% plotEye(sp, 1, 6, 'tx', 1)

%% Constellation
% close all;
% plot(sp.channelArray(1).rxSymbolMatched, '.')
% hold on;
% plot(sp.channelArray(1).rxCloudCenterMatched, 'x', 'markersize', 12, 'linewidth', 2)
% 
% figure;
% plot(sp.channelArray(1).rxSymbolRotated, '.')
% hold on;
% plot(sp.channelArray(1).rxCloudCenterRotated, 'x', 'markersize', 12, 'linewidth', 2)
plotConstellation(sp, 1, 'matched', 1)
plotConstellation(sp, 1, 'rotated', 2)