function simulateScenario(powerOOK1, powerOOK2, symbolRate1, symbolRate2, channelSpacing)
%% Simulation of OOK1+OOK2
% Variables:
% QAM power: -20:1:10 
% OOK power: -20:1:10 
% channel spacing: [50, 100, 150, 200] GHz
% OOK symbol rate: 10 GHz

%% Define links and channels
% S = 0.06 ps/(nm^2*km) = 60 s/m^3
linkArray = [...
    Link('spanLength', 82e3, 'DCFLength', 80e3, 'S', 60); ...
    Link('spanLength', 82e3, 'DCFLength', 80e3, 'S', 60); ...
    Link('spanLength', 82e3, 'DCFLength', 80e3, 'S', 60); ...
    Link('spanLength', 82e3, 'DCFLength', 80e3, 'S', 60); ...
    Link('spanLength', 82e3, 'DCFLength', 90e3, 'S', 60)];

ofbw1 = ceil(symbolRate1/50e9)*50e9;
ofbw2 = ceil(symbolRate2/50e9)*50e9;

channelArray = [...
    Channel('modulation', 'OOK', ...
    'centerFrequency', 0e9, ...
    'symbolRate', symbolRate1, ...
    'powerdBm', powerOOK1, ...
    'minNumberSymbol', 2^14, ...
    'opticalFilterBandwidth', ofbw1, ...
    'firFactor', 1); ...
    Channel('modulation', 'OOK', ...
    'centerFrequency', channelSpacing, ...
    'symbolRate', symbolRate2, ...
    'powerdBm', powerOOK2, ...
    'minNumberSymbol', 2^14, ...
    'opticalFilterBandwidth', ofbw2, ...
    'firFactor', 1)];

%%
simulationName = sprintf('Power1_%d_Power2_%d_symbolRate1_%d_symbolRate2_%d_channelSpacing_%d', ...
    powerOOK1, powerOOK2, symbolRate1/1e9, symbolRate2/1e9, channelSpacing/1e9);

sp = SinglePolarization(...
    'simulationName', simulationName, ...
    'simulationId', 1, ...
    'linkArray', linkArray, ...
    'channelArray', channelArray, ...
    'useParallel', false, ...
    'saveObject', false);
sp.simulate();
sp.saveSimulationResult(true, false, false);

end