function resultsLevel1150GHz = importfileResultsLevel1_150GHz(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   RESULTSLEVEL1150GHZ = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   RESULTSLEVEL1150GHZ = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   resultsLevel1150GHz = importfile('resultsLevel1_150GHz.csv', 2, 2773);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/02/23 19:51:36

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: categorical (%C)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%C%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
resultsLevel1150GHz = table(dataArray{1:end-1}, 'VariableNames', {'symbolRate_1','symbolRate_2','symbolRate_3','symbolRate_4','symbolRate_5','modulation','centerFrequency_1','centerFrequency_2','centerFrequency_3','centerFrequency_4','centerFrequency_5','powerdBm_1','powerdBm_2','powerdBm_3','powerdBm_4','powerdBm_5','SNR_1','SNR_2','SNR_3','SNR_4','SNR_5','SNRdB_1','SNRdB_2','SNRdB_3','SNRdB_4','SNRdB_5','EVM_1','EVM_2','EVM_3','EVM_4','EVM_5','SER_1','SER_2','SER_3','SER_4','SER_5','runningTime'});

